version: '3.4'

services:
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq
    ports:
    - "5672:5672"
    volumes:
    - rabbitmq:/var/lib/rabbitmq
    restart: on-failure

  redis:
    container_name: redis
    hostname: redis
    image: redis
    ports:
    - "6379:6379"
    volumes:
    - redis:/data
    restart: on-failure

  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
    - "5432:5432"
    volumes:
    - postgres-data:/var/lib/postgresql/data
    restart: on-failure

  django:
    build: .
    command: sh -c "./django_start.sh"
    container_name: django
    hostname: django
    image: test_task_django_image
    depends_on:
      - postgres
      - rabbitmq
    ports:
    - "8000:8000"
    volumes:
    - images:/usr/src/test_task/media/images
    restart: on-failure

  celery:
    command: sh -c "./celery_start.sh"
    container_name: celery
    hostname: celery
    image: test_task_django_image
    depends_on:
      - django
      - rabbitmq
      - redis
    volumes:
      - images:/usr/src/test_task/media/images
    restart: on-failure

volumes:
  postgres-data:
  rabbitmq:
  redis:
  images:
